#' Read directories of input tiles generated by create_subsets() into arrays for usage as input data
#'
#' @param inputdir String. Path to folder containing tile files.
#' @param dimensions 2D integer vector. Input size of images. Example: c(128, 128)
#' @param format String. File format for output. Format needs to be supported by raster library.
#'
#' @return Multidimensional arra of tile data.
#'
#' @examples \dontrun{readInput("C:/User/Desktop/Raster_Tiles/", c(128, 128), 6, ".tif")}
read_raster <- function(inputdir, dimensions, channels, format){

  # determine parameters of input data
  n_input <- length(list.files(inputdir, pattern = paste0(format)))

  # determine dimensions of input data
  input_size_x <- dimensions[1]
  input_size_y <- dimensions[2]

  # build array to hold data
  data <- array(dim = c(n_input, input_size_x, input_size_y, channels))

  # setting up progress reports
  percent_input <- (n_input / 100)
  print("Reading data:")
  progress_count <- 0

  # populate data array
  for(i in 1: n_input){
    # calculate part of file name according to naming conventions of createSubsets()
    lead <- (nchar(n_input) - nchar(i))
    zeros <- paste(replicate(lead, "0"), collapse = "")

    # read tile data into brick
    raster_file <- raster::brick(paste0(inputdir, "img_", zeros, i, format))

    # loop over channels to paste tile data into complete data array
    for(j in 1:channels){
      channel_matrix <- raster::as.matrix(raster::subset(raster_file, j))

      # paste matrix into data array
      data[i, , , j] <- channel_matrix[ , ]
    }

    # print progress of execution
    temp <- floor(i / percent_input)

    if(temp %% 10 == 0 && temp > 0 && temp > progress_count){
      print(paste0("Progress: ", temp, "%"))
      progress_count <- progress_count + 10
    }
  }


  return(data)
}


#' Prepare data for usage by reading tiles, masks and target data
#'
#' @param split Numeric value between 0 and 1. Represents train/test split percentage.
#' @param dimensions 2D vector of input image size. Example: c(128, 128).
#' @param channels Integer of channels in input image.
#'
#' @return Returns list of matrices, containing training and test tiles and masks.
#' @export
#'
#' @examples \dontrun{data <- prep_data(c(128, 128), 6)}
load_data <- function(tile_path = "F:/Master_Thesis/data/tiles/",
                      mask_path = "F:/Master_Thesis/data/masks/",
                      dimensions = c(128, 128), 
                      channels = 6){

  # read raster data
  tile_data <- read_raster(tile_path, dimensions, channels, ".tif")
  mask_data <- read_raster(mask_path, dimensions, 1, ".tif")

  # fill NAs with 0
  mask_data[is.na(mask_data)] <- 0

  # make list of arrays to return
  data <- list("tile_data" = tile_data, "mask_data" = mask_data)


  return(data)
}
